### ISSUE TITLE
Is anyone maintaining this? And can I move it to the Incubator?

### ISSUE THREAD

**Issue by LappleApple** [zalando-incubator/scala-study-group#2]

**Comment by dryewo** [comment]
This repo is not in use anymore. Please move it to the Incubator.

**Comment by okthatsneat** [comment]
I've downloaded it for safe keeping. will delete now.

**Comment by okthatsneat** [comment]
looks like i don't have autho to do so. who does?

**Comment by LappleApple** [comment]
I do. :)
